import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "./Providers";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar/Navbar";
import { AuthProvider } from "@/context/userData";
import StyledComponentsRegistry from "./StyledComponentsRegistry";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientProviders>
          <StyledComponentsRegistry>
            <AuthProvider>
              <Navbar />
              <Toaster
                position="top-center"
                reverseOrder={false}
              />
              {children}
              <Footer/>
            </AuthProvider>
          </StyledComponentsRegistry>
        </ClientProviders>
      </body>
    </html>
  );
}
